// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231004203922_Edit Order Identity")]
    partial class EditOrderIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Anytown, USA",
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 637, DateTimeKind.Local).AddTicks(8397),
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 637, DateTimeKind.Local).AddTicks(8408),
                            Password = "pIbiq9ROsk153rS9d4IeXgUd3hI7s6Y6yW5ZkevRwsZt3YhC",
                            PhoneNumber = "123-456-7890",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St, Anycity, USA",
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 641, DateTimeKind.Local).AddTicks(1419),
                            Email = "alice.smith@example.com",
                            FullName = "Alice Smith",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 641, DateTimeKind.Local).AddTicks(1428),
                            Password = "wT399xovW/5QZpQYDAMc+zolN2lVHqrwl3UKK48vC67wxT5F",
                            PhoneNumber = "987-654-3210",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 644, DateTimeKind.Local).AddTicks(2735),
                            Email = "lam@senik.com",
                            FullName = "Staff Lam",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 644, DateTimeKind.Local).AddTicks(2736),
                            Password = "Va+gFez4j1r7pIbfAwOuY0Tq0IivQPrLXk8zwmqNCceVsqHY",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 647, DateTimeKind.Local).AddTicks(4383),
                            Email = "hoanganh@senik.com",
                            FullName = "Staff Hoàng Anh",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 647, DateTimeKind.Local).AddTicks(4383),
                            Password = "Mg8FmD61VwMXmjyIamvTkUaHNLj59hUatBP3/o7c6BqcQfQP",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 650, DateTimeKind.Local).AddTicks(6055),
                            Email = "thong@senik.com",
                            FullName = "Staff Thông",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 650, DateTimeKind.Local).AddTicks(6055),
                            Password = "tPPJWChEAW18FexXKDZMVLBZ4ZkjzmbQIF9BBnX38Kk8M8UT",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("TotalMoney")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("TotalQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3781),
                            Description = "A stunning succulent that glows like the moonlight.",
                            Image = "https://th.bing.com/th/id/OIP.xMeFmNxgcpdd5sXMfXIi-gHaE7?pid=ImgDet&w=800&h=533&rs=1",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3792),
                            Name = "Mystical Moonlight Succulent",
                            Price = 97000.0,
                            Quantity = 50,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3794),
                            Description = "An illusionary cactus that appears to shimmer in the desert sun.",
                            Image = "https://th.bing.com/th/id/OIP.hNc2N9iLljV8VMWx_BHJ7QEDDw?pid=ImgDet&rs=1",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3795),
                            Name = "Desert Mirage Cactus",
                            Price = 12000.0,
                            Quantity = 30,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3796),
                            Description = "Create a magical atmosphere with these enchanting fairy lights",
                            Image = "https://th.bing.com/th/id/OIP.2Kpj8zaosbOUIfX0AmSlMgHaHa?pid=ImgDet&rs=1",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3797),
                            Name = "Enchanted Forest Fairy Lights",
                            Price = 75000.0,
                            Quantity = 20,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3798),
                            Description = "A succulent that resembles the fiery scales of a dragon.",
                            Image = "https://th.bing.com/th/id/OIP.YPEnYKS5Od0Hk2c5x6MH4QHaE8?pid=ImgDet&rs=1",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3798),
                            Name = "Fire Dragon Succulent",
                            Price = 86000.0,
                            Quantity = 45,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3800),
                            Description = "A beautifully crafted glass vase inspired by the ocean.",
                            Image = "https://i.pinimg.com/originals/ce/ef/a2/ceefa2a3524afedbe6d99fa19bacd437.jpg",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3800),
                            Name = "Ocean Breeze Glass Vase",
                            Price = 55000.0,
                            Quantity = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3802),
                            Description = "A cactus that emits a neon-like glow in the dark.",
                            Image = "https://th.bing.com/th/id/R.b8d267e5efaf29425e5b7747cc6fd413?rik=Dj%2fXfb2WHH53wg&riu=http%3a%2f%2fstatic1.squarespace.com%2fstatic%2f51a79166e4b01ba7ba19a0f6%2ft%2f56f9e1101330bacc0f95b928%2f1459216677818%2f&ehk=IAXClID1p4n%2f%2bopYz6b6PwqITx0R9RveUHC1EjxJLFc%3d&risl=&pid=ImgRaw&r=0",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3802),
                            Name = "Neon Glow Cactus",
                            Price = 11000.0,
                            Quantity = 28,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3804),
                            Description = "Create your own starry night with this succulent garden.",
                            Image = "https://i.pinimg.com/736x/37/2f/9f/372f9fa78e0cdf9b0141bce4dfc7dd23.jpg",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3804),
                            Name = "Starry Night Succulent Garden",
                            Price = 275000.0,
                            Quantity = 40,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = 3,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3806),
                            Description = "A crystal-clear globe that adds elegance to your decor.",
                            Image = "https://th.bing.com/th/id/OIP.sJ0mfVF7ptta-BZmzhAcjgAAAA?pid=ImgDet&rs=1",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3806),
                            Name = "Crystal Clear Decorative Globe",
                            Price = 55000.0,
                            Quantity = 22,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3807),
                            Description = "An elegantly designed crystal vase fit for royalty.",
                            Image = "https://a.1stdibscdn.com/archivesE/upload/7977/26_15/2493352/2493352_l.jpeg",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3808),
                            Name = "Royal Elegance Crystal Vase",
                            Price = 65000.0,
                            Quantity = 18,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            CreationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3809),
                            Description = "A rugged cactus reminiscent of the wild west landscapes.",
                            Image = "https://th.bing.com/th/id/OIP.ez7XcMIuvhJd8LERpka5CwHaE7?pid=ImgDet&rs=1",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 5, 3, 39, 22, 655, DateTimeKind.Local).AddTicks(3810),
                            Name = "Wild West Prickly Pear Cactus",
                            Price = 75000.0,
                            Quantity = 35,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.HasOne("Domain.Account", "CustomerInfor")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CustomerInfor");
                });

            modelBuilder.Entity("Domain.OrderDetail", b =>
                {
                    b.HasOne("Domain.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Account", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
